language: cpp
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get install libeigen3-dev
  - sudo apt-get install gfortran
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
